spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_mc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl