spring:
  datasource:
    url: jdbc:mysql://10.2.2.3:3306/prod_mc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: dev_readonly
    password: YXdev)*@$
    driverClassName: com.mysql.cj.jdbc.Driver